//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 03:48:39 PM CEST 
//


package xml.web_services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.web_services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.web_services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetReservationsRequest }
     * 
     */
    public GetReservationsRequest createGetReservationsRequest() {
        return new GetReservationsRequest();
    }

    /**
     * Create an instance of {@link SendReplyRequest }
     * 
     */
    public SendReplyRequest createSendReplyRequest() {
        return new SendReplyRequest();
    }

    /**
     * Create an instance of {@link Reply }
     * 
     */
    public Reply createReply() {
        return new Reply();
    }

    /**
     * Create an instance of {@link GetAccomodationCategoryRequest }
     * 
     */
    public GetAccomodationCategoryRequest createGetAccomodationCategoryRequest() {
        return new GetAccomodationCategoryRequest();
    }

    /**
     * Create an instance of {@link GetReservationsResponse }
     * 
     */
    public GetReservationsResponse createGetReservationsResponse() {
        return new GetReservationsResponse();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link GetReviewsResponse }
     * 
     */
    public GetReviewsResponse createGetReviewsResponse() {
        return new GetReviewsResponse();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link GetAccomodationTypeResponse }
     * 
     */
    public GetAccomodationTypeResponse createGetAccomodationTypeResponse() {
        return new GetAccomodationTypeResponse();
    }

    /**
     * Create an instance of {@link AccomodationType }
     * 
     */
    public AccomodationType createAccomodationType() {
        return new AccomodationType();
    }

    /**
     * Create an instance of {@link GetAccomodationTypeRequest }
     * 
     */
    public GetAccomodationTypeRequest createGetAccomodationTypeRequest() {
        return new GetAccomodationTypeRequest();
    }

    /**
     * Create an instance of {@link SendReplyResponse }
     * 
     */
    public SendReplyResponse createSendReplyResponse() {
        return new SendReplyResponse();
    }

    /**
     * Create an instance of {@link SendAccomodationResponse }
     * 
     */
    public SendAccomodationResponse createSendAccomodationResponse() {
        return new SendAccomodationResponse();
    }

    /**
     * Create an instance of {@link TryReservationRequest }
     * 
     */
    public TryReservationRequest createTryReservationRequest() {
        return new TryReservationRequest();
    }

    /**
     * Create an instance of {@link GetMessagesResponse }
     * 
     */
    public GetMessagesResponse createGetMessagesResponse() {
        return new GetMessagesResponse();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link GetReviewsRequest }
     * 
     */
    public GetReviewsRequest createGetReviewsRequest() {
        return new GetReviewsRequest();
    }

    /**
     * Create an instance of {@link GetMessagesRequest }
     * 
     */
    public GetMessagesRequest createGetMessagesRequest() {
        return new GetMessagesRequest();
    }

    /**
     * Create an instance of {@link SendReservationsRequest }
     * 
     */
    public SendReservationsRequest createSendReservationsRequest() {
        return new SendReservationsRequest();
    }

    /**
     * Create an instance of {@link SendAccomodationRequest }
     * 
     */
    public SendAccomodationRequest createSendAccomodationRequest() {
        return new SendAccomodationRequest();
    }

    /**
     * Create an instance of {@link Accomodation }
     * 
     */
    public Accomodation createAccomodation() {
        return new Accomodation();
    }

    /**
     * Create an instance of {@link GetAccomodationCategoryResponse }
     * 
     */
    public GetAccomodationCategoryResponse createGetAccomodationCategoryResponse() {
        return new GetAccomodationCategoryResponse();
    }

    /**
     * Create an instance of {@link AccomodationCategory }
     * 
     */
    public AccomodationCategory createAccomodationCategory() {
        return new AccomodationCategory();
    }

    /**
     * Create an instance of {@link SendReservationsResponse }
     * 
     */
    public SendReservationsResponse createSendReservationsResponse() {
        return new SendReservationsResponse();
    }

    /**
     * Create an instance of {@link TryReservationResponse }
     * 
     */
    public TryReservationResponse createTryReservationResponse() {
        return new TryReservationResponse();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Adress }
     * 
     */
    public Adress createAdress() {
        return new Adress();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link PricePlan }
     * 
     */
    public PricePlan createPricePlan() {
        return new PricePlan();
    }

}
